### ISSUE TITLE
HTTP 411 content-lenght in header

### ISSUE THREAD

**Issue by jeremfg** [corux/scm-fisheye-plugin#1]
Hello again, 3 years later ;-)

I'm the one who reported the issue below a long time ago:
https://groups.google.com/forum/#!topic/scmmanager/0oPJQjfvLuU

After all these years we're in the process of migrating our installation of scm-manager to a new server, and at the same time, upgrading from version 1.41 to 1.56.
During all this time we've apparently been using the custom SNAPSHOT build you had made for us.

Obviously on our new installation of scm-manager we've installed the latest version of the scm-fisheye-plugin (version 1.3). However it seems this old issue still exists. I get the following in **scm-manager.log**:

```
2018-01-18 14:37:35.955 [EventBus-10] INFO  sonia.scm.repository.LastModifiedUpdateListener - update last modified date of repository DIP8QexuR1

2018-01-18 14:37:35.955 [EventBus-10] INFO  sonia.scm.repository.DefaultRepositoryManager - modify repository test-push_notifications of type git

2018-01-18 14:37:35.972 [Hook-1] INFO  sonia.scm.jenkins.JenkinsGlobalHookHandler - request returned 200
2018-01-18 14:37:36.255 [Hook-0] WARN  de.corux.scm.plugins.fisheye.client.FisheyeClient - Fisheye hook failed with statusCode 411

2018-01-18 14:37:36.255 [Hook-0] ERROR de.corux.scm.plugins.fisheye.FisheyeHook - Failed to execute fisheye hook. SCM repository: test-push_notifications, Fisheye repository: Dummy_Test_PushNotifications

2018-01-18 14:51:30.514 [qtp739498517-32] INFO  sonia.scm.plugin.DefaultPluginManager - fetch plugin informations from http://plugins.scm-manager.org/scm-plugin-backend/api/1.56/plugins?os=Linux&arch=64&snapshot=false
```

If my understanding is correct, your plugin would have needed to adapt to a new API, as described here:
https://bitbucket.org/sdorra/scm-manager/issues/709/extend-httpclient-to-allow-arbitrary

Any idea why we're still getting this issue (or why we apparently are the only one who encounters it?)
FYI we are now using version of 4.2.0 of Fisheye nowadays.

**Comment by jeremfg** [comment]
FYI... I've put back the old 1.1-SNAPSHOT from april 2015 and it fixes my issue

**Comment by corux** [comment]
Hello again :-)
looks like the issue with Content-Length and IIS still exists, even with the updated scm-manager API. I've implemented the fix and created a new snapshot version: 
[scm-fisheye-plugin-1.4-SNAPSHOT.zip](https://github.com/corux/scm-fisheye-plugin/files/1648225/scm-fisheye-plugin-1.4-SNAPSHOT.zip)

Please check if this version fixes your issue. If so, I'll create a new release out of it.

FYI, I had no issues running Fisheye behind an Nginx or Apache reverse proxy.

**Comment by jeremfg** [comment]
Oh right... I had forgotten IIS was involved in there somewhere. Oh well...
I've just tried your new snapshot and it seems to work as expected.

Thanks for your prompt reply. Much appreciated!

**Comment by corux** [comment]
Version 1.4 is now released. I'm glad to help out!

**Comment by jeremfg** [comment]
I can't explain why, but suddenly it doesn't work with the official 1.4 release.
I get the following stack trace:

```
2018-01-22 10:43:55.518 [qtp739498517-30] WARN  org.apache.shiro.mgt.DefaultSecurityManager - Delegate RememberMeManager instance of type [org.apache.shiro.web.mgt.CookieRememberMeManager] threw an exception during getRememberedPrincipals().
org.apache.shiro.crypto.CryptoException: Unable to execute 'doFinal' with cipher instance [javax.crypto.Cipher@14b052a8].
        at org.apache.shiro.crypto.JcaCipherService.crypt(JcaCipherService.java:462)
        at org.apache.shiro.crypto.JcaCipherService.crypt(JcaCipherService.java:445)
        at org.apache.shiro.crypto.JcaCipherService.decrypt(JcaCipherService.java:390)
        at org.apache.shiro.crypto.JcaCipherService.decrypt(JcaCipherService.java:382)
        at org.apache.shiro.mgt.AbstractRememberMeManager.decrypt(AbstractRememberMeManager.java:479)
        at org.apache.shiro.mgt.AbstractRememberMeManager.convertBytesToPrincipals(AbstractRememberMeManager.java:419)
        at org.apache.shiro.mgt.AbstractRememberMeManager.getRememberedPrincipals(AbstractRememberMeManager.java:386)
        at org.apache.shiro.mgt.DefaultSecurityManager.getRememberedIdentity(DefaultSecurityManager.java:604)
        at org.apache.shiro.mgt.DefaultSecurityManager.resolvePrincipals(DefaultSecurityManager.java:492)
        at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:342)
        at org.apache.shiro.subject.Subject$Builder.buildSubject(Subject.java:846)
        at org.apache.shiro.web.subject.WebSubject$Builder.buildWebSubject(WebSubject.java:148)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.createSubject(AbstractShiroFilter.java:292)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:359)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at sonia.scm.boot.BootstrapFilter.doFilter(BootstrapFilter.java:119)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:556)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:369)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:464)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:913)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:975)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:641)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:231)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at javax.crypto.Cipher.doFinal(Cipher.java:2165)
        at org.apache.shiro.crypto.JcaCipherService.crypt(JcaCipherService.java:459)
        ... 44 common frames omitted
```

**Comment by jeremfg** [comment]
I realize it makes little sense (I saw your Git history showing only changes to the pom file between the two versions). But I confirm that reverting back to 1.4-SNAPSHOT works.

I'm dumbfounded... Is something different about the build itself?

**Comment by corux** [comment]
The stack trace seems to be related to the "remember me" cookie. Do you have another error in your log?
Both the snapshot and the release builds contain the same fix, so both should work the same.

**Comment by jeremfg** [comment]
I've looked back at every concurrence in the logs, and once it was accompanied with the following traces:
```
2018-01-22 10:38:15.126 [qtp739498517-30] INFO  sonia.scm.plugin.AetherPluginHandler - try to uninstall plugin: sonia.scm.plugins:scm-fisheye-plugin:1.4-SNAPSHOT

2018-01-22 10:38:15.129 [qtp739498517-30] INFO  sonia.scm.plugin.AetherDependencyResolver - create repository system session

2018-01-22 10:38:17.745 [qtp739498517-30] INFO  sonia.scm.plugin.AetherPluginHandler - try to install plugin with gav: sonia.scm.plugins:scm-fisheye-plugin:1.4

2018-01-22 10:38:17.745 [qtp739498517-30] INFO  sonia.scm.plugin.AetherDependencyResolver - create repository system session
```
I was wondering if it had something to do with the version of the JDK used to create the release vs the snapshot, hence my earlier question.
FYI, I'm using OpenJDK's JRE, version 1.8.0_151-b12 on that server.

In any case I've attached the whole log file. All I know is that this stacktrace occurs on the exact second I perform my Git push, and this disappears when I revert back to 1.4-SNAPSHOT.

[scm-manager.log](https://github.com/corux/scm-fisheye-plugin/files/1653558/scm-manager.log)

**Comment by corux** [comment]
From the logs, it seems like the Fisheye hook is not active for your git repository:
```
2018-01-22 11:08:23.324 [EventBus-0] INFO  sonia.scm.repository.DefaultRepositoryManager - modify repository test-push_notifications of type git
2018-01-22 11:08:23.356 [Hook-1] INFO  sonia.scm.jenkins.JenkinsGlobalHookHandler - request returned 200
```
It should contain some messages regarding the fisheye plugin, like:
```
2018-01-22 22:51:52.860 [EventBus-0] INFO  sonia.scm.repository.DefaultRepositoryManager - modify repository test of type git
2018-01-22 22:51:52.952 [Hook-0] WARN  de.corux.scm.plugins.fisheye.client.FisheyeClient - Fisheye hook failed with statusCode 302
2018-01-22 22:51:52.953 [Hook-0] ERROR de.corux.scm.plugins.fisheye.FisheyeHook - Failed to execute fisheye hook. SCM repository: test, Fisheye repository: test
```

Please check your Fisheye configuration under "General" and on your repository.

**Comment by jeremfg** [comment]
I agree it should show traces from the Fisheye plugin, I have seen them before.
So yes, I'm a bit confused but it looks like these traces aren't printed anymore.

For example I have the following traces:
```
2018-01-23 15:46:01.165 [qtp739498517-98124] WARN  sonia.scm.web.filter.BasicAuthenticationFilter - authentication failed for user Username for 'https

2018-01-23 15:46:41.276 [qtp739498517-96545] WARN  sonia.scm.web.filter.BasicAuthenticationFilter - username or password is null/empty

2018-01-23 15:46:46.085 [qtp739498517-96545] WARN  sonia.scm.web.filter.BasicAuthenticationFilter - username or password is null/empty

2018-01-23 15:46:46.534 [EventBus-529] INFO  sonia.scm.web.security.DefaultAdministrationContext - user slatulippe executes sonia.scm.repository.LastModifiedUpdateListener$LastModifiedPrivilegedAction as admin

2018-01-23 15:46:46.535 [EventBus-529] INFO  sonia.scm.repository.LastModifiedUpdateListener - update last modified date of repository 89P5thTvF9

2018-01-23 15:46:46.535 [EventBus-529] INFO  sonia.scm.repository.DefaultRepositoryManager - modify repository smv6-6lr-core of type git

2018-01-23 15:46:46.850 [Hook-223] INFO  sonia.scm.web.security.DefaultAdministrationContext - user slatulippe executes sonia.scm.authormapping.MappingPrivilegedAction as admin

2018-01-23 15:46:55.459 [qtp739498517-98128] WARN  sonia.scm.web.filter.BasicAuthenticationFilter - username or password is null/empty

2018-01-23 15:46:59.136 [qtp739498517-98124] WARN  sonia.scm.web.filter.BasicAuthenticationFilter - username or password is null/empty

2018-01-23 15:47:54.377 [EventBus-534] INFO  sonia.scm.web.security.DefaultAdministrationContext - user mbaril executes 
```
And yet, Fisheye was successfully notified and ran an incremental index as if the pluign ran successfully.

I seem to only get error logs, when a repository is NOT configured and the notification expectedly fails, such as:
```
2018-01-23 13:32:19.993 [EventBus-433] INFO  sonia.scm.web.security.DefaultAdministrationContext - user RVadlamani executes sonia.scm.repository.LastModifiedUpdateListener$LastModifiedPrivilegedAction as admin

2018-01-23 13:32:19.994 [EventBus-433] INFO  sonia.scm.repository.LastModifiedUpdateListener - update last modified date of repository 7RPX9zRiED

2018-01-23 13:32:19.994 [EventBus-433] INFO  sonia.scm.repository.DefaultRepositoryManager - modify repository automation/SecureMeshSEALTest of type git

2018-01-23 13:32:20.001 [Hook-171] WARN  de.corux.scm.plugins.fisheye.client.FisheyeClient - Fisheye hook failed with statusCode 404

2018-01-23 13:32:20.001 [Hook-171] ERROR de.corux.scm.plugins.fisheye.FisheyeHook - Failed to execute fisheye hook. SCM repository: automation/SecureMeshSEALTest, Fisheye repository: automation/SecureMeshSEALTest

2018-01-23 13:32:20.006 [Hook-172] INFO  sonia.scm.jenkins.JenkinsGlobalHookHandler - request returned 200
```

I really don't know what to say... It's as if everything is screwed up on my side.

FYI... This is all running 1.4-SNAPSHOT, the version of the plugin that currently works for me.

**Comment by corux** [comment]
Looks like the log-level should be increased. Compare https://bitbucket.org/sdorra/scm-manager/wiki/faq
You'll need `<root level="INFO">` and optionally `<logger name="sonia.scm" level="DEBUG" />`.
With these logging options you'll see the following messages:
```
2018-01-24 18:26:16.461 [Hook-1] DEBUG sonia.scm.repository.RepositoryHookTask - execute async POST_RECEIVE hook de.corux.scm.plugins.fisheye.FisheyeHook for repository Test
2018-01-24 18:26:16.464 [Hook-1] DEBUG sonia.scm.net.ahc.DefaultAdvancedHttpClient - fetch https://xxxx/rest-service-fecru/admin/repositories/Test/incremental-index
2018-01-24 18:26:16.661 [Hook-1] INFO  de.corux.scm.plugins.fisheye.FisheyeHook - Successfully executed fisheye hook. SCM repository: Test, Fisheye repository: Test
```

I've tested this with release 1.4 and the scm-manager 1.56. My environment is Linux and Oracle Server JRE 1.8.0_151. Also tested it with scm-manager on OpenJDK 1.8.0_151 with the same results.
